### PR TITLE
SLING-9045 - Rebase of PR #1 - Adding option to disable URL params check

### PR DESCRIPTION
**Pull request by jfmitchell**
All credit to @srgovindaraj for the changes.

I'm championing this PR - since it complements the ignoreUrlParams option in the dispatcher for highly cachable sites.

### CODE REVIEW

**Comment by jfmitchell** [comment]
#13 is the original PR

**Comment by rombert** [comment]
Thanks for picking this up @jfmitchell ! Some notes:

# the build fails ( see Jenkins check ) - `[ERROR] org.apache.sling.dynamicinclude: Version increase required; detected 4.2.1, suggested 4.3.0`
# the branch cannot be rebased due to conflicts; please squash all commits into one and then rebase
# you can credit the original author, for instance by using `Originally-By: <email>` in the commit message

Otherwise changes LGTM.

**Comment by rombert** [comment]
... and note that I merged the PR that removes the package exports, so you do not need to handle issue 1 from my comment above.

**Comment by jfmitchell** [comment]
@rombert All done.

**Comment by jfmitchell** [comment]
@rombert All done

**Comment by rombert** [comment]
Merged, thanks @jfmitchell !

**Comment by geetika95** [comment]
We tried testing this feature in one of the projects, SDI functionality doesn't seem to work at all. Even the default behavior of SDI without the URL params is not working with the latest version. Is there any special configuration we need to do/add to make it work?

Current Version: 3.2.0 with AEM 6.5.3 (Functionality not working at all)
Previous Version: 3.1.2 with AEM 6.5.3 (Working as expected)

**Comment by rombert** [comment]
@geetika95 - please file a bug report on the Sling issue tracker about this, with steps to reproduce. Thanks!

**Comment by geetika95** [comment]
Thanks @rombert, I created the ticket, here it is https://issues.apache.org/jira/browse/SLING-9634

**Pull request merged**
