### PR TITLE
Option to disable the URL params check when there is need to process all GET requests

### PR DESCRIPTION
**Pull request by srgovindaraj**
Hi @rombert, @justinedelson, @ieb, @bdelacretaz and @raducotescu 

Good day...

I have requested this new property in SDI to allow support for users who are connecting while commuting (via low bandwidth networks). Enabling this new property in OSGi console will enable **Sling Dynamic Include** for all GET requests and allow us to maximize the dispatcher caching utilization for all GET requests.

We are currently using customized SDI (please see the PR changes) for our website and we would like to get this option included in original SDI repo itself. 
We felt that this custom option would beneficial for others as well.

So that our team can continue using the SDI from apache and will get the benefits/bugfixes from future apache SDI release.

Thanks,
GovindR.

### CODE REVIEW

**Comment by jfmitchell** [comment]
This is great - but what might be better is if we had a mechanism that mirrored the ignoreUrlParams configuration in the dispatcher - so they could effectively be kept in sync.

**Comment by jasper-s** [comment]
This feature would come in real handy in some of our projects as well!

**Comment by rombert** [comment]
I see that the PR no longer merges cleanly, and also the build check failed. It would be good is someone could rebase it and make sure it builds.

**Comment by jfmitchell** [comment]
I'll sort it out. I reached out to @srgovindaraj  before - because I didn't want to steal his thunder - but I'll get it rebased shortly.

**Comment by jfmitchell** [comment]
I don't have the permission to modify this existing PR - so I've created a separate one.

**Comment by rombert** [comment]
Closing in favour of #13

**Pull request closed without merging**
